apiVersion: v1
kind: ReplicationController
metadata:
  name: my-go-app-rc
spec:
  replicas: 5
  selector:
    app: my-go-app
  template:
    metadata:
      name: my-go-app
      labels:
        app: my-go-app
    spec:
      containers:
      - name: my-go-app
        image: my-go-app
        ports:
        - containerPort: 80
